### ISSUE TITLE
License Selection

### ISSUE THREAD

**Issue by dusty736** [UBC-MDS/pictureperrrfect#30]
We have decided to go with an MIT license because:
- We want our package to be simple and permissive
- Freely availble to future MDS students as a reference
- We don't want to be held liable or provide warranty
- The package is a reimplementation of other more efficient packages so there isn't any commerical use for what we are creating other than teaching purposes

"The MIT License is short and to the point. It lets people do almost anything they want with your project, like making and distributing closed source versions."
- https://choosealicense.com/

**Comment by ChadNeald** [comment]
Our package is also a reimplementation of image packages that already exist so we didn't feel the need to pick a more specialized license.

**Comment by KangboLu** [comment]
I am good with MIT license 👍

**Comment by ChadNeald** [comment]
We don't want to provide any warranty since we are not going to be updating this code moving forward. We also don't want to be held liable for any problems with our code. We are also fine if people use or reference our code especially considering future MDS students may be looking to this project as an example.
